#!/bin/bash
# $Author$
# $Revision$
# $Date$

PORT=9998

# start slave processes (one/CPU)
declare -i i
for (( i=0; $i < $CPUS; i++ )); do
   echo Starting slave $i
   ( sleep 1; SPECturbo.Release localhost:$PORT >/dev/null 2>&1 )&
done

# start master process
echo Starting master
SPECturbo.Release :$PORT
