#!/bin/bash
# $Author$
# $Revision$
# $Date$

# Usage: runSPECturbo [Port [Count [Release]]]

if [[ $# > 0 ]]; then
   PORT=$1
else
   PORT=9998
fi

if [[ $# > 1 ]]; then
   COUNT=$2
else
   COUNT=$CPUS
fi

if [[ $# > 2 ]]; then
   RELEASE=$3
else
   RELEASE=Release
fi

# start slave processes (one/CPU)
declare -i i
for (( i=0; $i < $COUNT; i++ )); do
   echo Starting slave $i
   ( sleep 1; SPECturbo.$RELEASE localhost:$PORT >/dev/null 2>&1 )&
done

# start master process
echo Starting master
SPECturbo.$RELEASE :$PORT
