FROM ubuntu:20.04

# NOTE
# Important that apt-get update AND apt-get install are run in the same command
# to ensure that the docker file installs the latest package versions. The rm
# /var/lib/apt/lists/* command is to clean up the apt cache which reduces the
# image size.

# Install necessary packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=UTC apt-get install -y \
    bear \
    build-essential \
    g++ \
    gcc \
    gdb \
    git \
    libboost-all-dev \
    tree \
    vim \
    && apt-get autoclean && apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash sc -p simcommsys

USER sc
WORKDIR /home/sc

# Creating the workspace folder
RUN mkdir -p ~/simCommSys
