executor:
  type: masterslave

jobs:
  mygroup:
    base_dir: ..
    glob: Simulators/*.txt
    output_dir: Results
    param_ranges:
      - 1.5:0.1:11.1:arithmetic
    confidence: 0.95
    relative_error: 0.05
    floor_min: 1e-5
    # job params
    simcommsys_tag: development
    simcommsys_type: release
    port: 3002
    workers: 8
