executor:
  type: slurm
  email: mark.mizzi.19+slurm@um.edu.mt
  account: qkd
jobs:
  # Timing measurements
  mygroup:
    glob: ../Simulators/*.txt
    output_dir: "../Results"
    param_ranges:
      - 1.5:0.1:11.1:arithmetic
    confidence: 0.95
    relative_error: 0.05
    floor_min: 1e-5
    # job params
    simcommsys_tag: development
    simcommsys_type: release
    partition: research_cpu
    memlimit_gb: 50
    timeout_mins: 8640 # 10 days
    nodelist: nyquist
    cpus_per_task: 1
